apiVersion: "storage.k8s.io/v1"
kind: "StorageClass"
metadata:
  name: "sc-rabbitmq"
provisioner: "rabbitmq/external-nfs"
parameters:
  server: "10.4.97.1"
  path: "/mnt/nfs"
  readOnly: "false"

---

apiVersion: "v1"
kind: "PersistentVolume"
metadata:
  name: "pv-rabbitmq"
spec:
  capacity:
    storage: "8Gi"
  volumeMode: "Filesystem"
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: "Retain"
  storageClassName: "sc-rabbitmq"
  mountOptions:
    - hard
  nfs:
    path: "/mnt/nfs"
    server: "10.4.97.1"
    
---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-rabbitmq
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 8Gi
  storageClassName: sc-rabbitmq
  volumeName: "rabbitmq"