apiVersion: "storage.k8s.io/v1"
kind: "StorageClass"
metadata:
  name: "sc-catalogue"
provisioner: "catalogue/external-nfs"
parameters:
  server: "10.4.97.1"
  path: "/mnt/nfs"
  readOnly: "false"

---
apiVersion: "v1"
kind: "PersistentVolume"
metadata:
  name: "pv-catalogue"
spec:
  capacity:
    storage: "8Gi"
  volumeMode: "Filesystem"
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: "Retain"
  storageClassName: "sc-catalogue"
  mountOptions:
    - hard
  nfs:
    path: "/mnt/nfs"
    server: "10.4.97.1"

---

kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: mssql-data
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 8Gi