---

kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: sc-manual
provisioner: cluster.local/nfs-subdir-external-provisioner
volumeBindingMode: WaitForFirstConsumer

---

apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-keycloak
spec:
  storageClassName: sc-manual
  capacity:
    storage: 10Gi
  accessModes:
  - ReadWriteOnce
  hostPath:
    path: /mnt/nfs

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: data-keycloak-postgresql-0
spec:
  storageClassName: sc-manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi